-- MySQL Script generated by MySQL Workbench
-- Sat May  4 13:44:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SANTIAGOA_TEST
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SANTIAGOA_TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SANTIAGOA_TEST` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` ;
USE `SANTIAGOA_TEST` ;

-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_categoria_idx` (`categoria_id` ASC) ,
  CONSTRAINT `fk_usuarios_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `SANTIAGOA_TEST`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`unidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `cupo_max` VARCHAR(45) NOT NULL,
  `unidades_id` INT NOT NULL,
  PRIMARY KEY (`id`, `unidades_id`),
  INDEX `fk_cursos_unidades1_idx` (`unidades_id` ASC) ,
  CONSTRAINT `fk_cursos_unidades1`
    FOREIGN KEY (`unidades_id`)
    REFERENCES `SANTIAGOA_TEST`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`clases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `marca_confirmacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`bloques` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `visibilidad` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`bloques_has_clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`bloques_has_clases` (
  `bloques_id` INT NOT NULL,
  `clases_id` INT NOT NULL,
  PRIMARY KEY (`bloques_id`, `clases_id`),
  INDEX `fk_bloques_has_clases_clases1_idx` (`clases_id` ASC) ,
  INDEX `fk_bloques_has_clases_bloques1_idx` (`bloques_id` ASC) ,
  CONSTRAINT `fk_bloques_has_clases_bloques1`
    FOREIGN KEY (`bloques_id`)
    REFERENCES `SANTIAGOA_TEST`.`bloques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bloques_has_clases_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `SANTIAGOA_TEST`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`clases_has_unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`clases_has_unidades` (
  `clases_id` INT NOT NULL,
  `unidades_id` INT NOT NULL,
  PRIMARY KEY (`clases_id`, `unidades_id`),
  INDEX `fk_clases_has_unidades_unidades1_idx` (`unidades_id` ASC) ,
  INDEX `fk_clases_has_unidades_clases1_idx` (`clases_id` ASC) ,
  CONSTRAINT `fk_clases_has_unidades_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `SANTIAGOA_TEST`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clases_has_unidades_unidades1`
    FOREIGN KEY (`unidades_id`)
    REFERENCES `SANTIAGOA_TEST`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SANTIAGOA_TEST`.`usuarios_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SANTIAGOA_TEST`.`usuarios_has_cursos` (
  `usuarios_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `cursos_unidades_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `cursos_id`, `cursos_unidades_id`),
  INDEX `fk_usuarios_has_cursos_cursos1_idx` (`cursos_id` ASC, `cursos_unidades_id` ASC) ,
  INDEX `fk_usuarios_has_cursos_usuarios1_idx` (`usuarios_id` ASC) ,
  CONSTRAINT `fk_usuarios_has_cursos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `SANTIAGOA_TEST`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id` , `cursos_unidades_id`)
    REFERENCES `SANTIAGOA_TEST`.`cursos` (`id` , `unidades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`genres` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `ranking` INT(10) UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `genres_ranking_unique` (`ranking` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) NOT NULL,
  `rating` DECIMAL(3,1) UNSIGNED NOT NULL,
  `awards` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `release_date` DATETIME NOT NULL,
  `length` INT(10) UNSIGNED NULL DEFAULT NULL,
  `genre_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `movies_genre_id_foreign` (`genre_id` ASC) ,
  CONSTRAINT `movies_genre_id_foreign`
    FOREIGN KEY (`genre_id`)
    REFERENCES `movies_db`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`actors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `rating` DECIMAL(3,1) NULL DEFAULT NULL,
  `favorite_movie_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `actors_favorite_movie_id_foreign` (`favorite_movie_id` ASC) ,
  CONSTRAINT `actors_favorite_movie_id_foreign`
    FOREIGN KEY (`favorite_movie_id`)
    REFERENCES `movies_db`.`movies` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`series` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) NOT NULL,
  `release_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `genre_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `series_genre_id_foreign` (`genre_id` ASC) ,
  CONSTRAINT `series_genre_id_foreign`
    FOREIGN KEY (`genre_id`)
    REFERENCES `movies_db`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`seasons` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) NULL DEFAULT NULL,
  `number` INT(10) UNSIGNED NULL DEFAULT NULL,
  `release_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `serie_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `seasons_serie_id_foreign` (`serie_id` ASC) ,
  CONSTRAINT `seasons_serie_id_foreign`
    FOREIGN KEY (`serie_id`)
    REFERENCES `movies_db`.`series` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`episodes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) NULL DEFAULT NULL,
  `number` INT(10) UNSIGNED NULL DEFAULT NULL,
  `release_date` DATETIME NOT NULL,
  `rating` DECIMAL(3,1) NOT NULL,
  `season_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `episodes_season_id_foreign` (`season_id` ASC) ,
  CONSTRAINT `episodes_season_id_foreign`
    FOREIGN KEY (`season_id`)
    REFERENCES `movies_db`.`seasons` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`actor_episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`actor_episode` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `actor_id` INT(10) UNSIGNED NOT NULL,
  `episode_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `actor_episode_actor_id_foreign` (`actor_id` ASC) ,
  INDEX `actor_episode_episode_id_foreign` (`episode_id` ASC) ,
  CONSTRAINT `actor_episode_actor_id_foreign`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movies_db`.`actors` (`id`),
  CONSTRAINT `actor_episode_episode_id_foreign`
    FOREIGN KEY (`episode_id`)
    REFERENCES `movies_db`.`episodes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 149
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`actor_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`actor_movie` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `actor_id` INT(10) UNSIGNED NOT NULL,
  `movie_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `actor_movie_actor_id_foreign` (`actor_id` ASC) ,
  INDEX `actor_movie_movie_id_foreign` (`movie_id` ASC) ,
  CONSTRAINT `actor_movie_actor_id_foreign`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movies_db`.`actors` (`id`),
  CONSTRAINT `actor_movie_movie_id_foreign`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies_db`.`movies` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) ,
  INDEX `password_resets_token_index` (`token` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
